---
- name: create user
  hosts: webservers
  tasks:
    - name: create user in ubuntu
      user:
        name: ansible_user
        password: "{{ 'password' | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes
        home: /home/ansible_user
        groups: sudo
        append: yes
        state: present
        system: no
      when: ansible_distribution in ["Ubuntu"]

    - name: create user in rocky
      user:
        name: ansible_user
        password: "{{ 'password' | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes
        home: /home/ansible_user
        groups: wheel
        append: yes
        state: present
        system: no
      when: ansible_distribution in ["Rocky"]

    - name: copy .ssh directory over
      copy: 
        remote_src: yes
        src: /root/.ssh/
        dest: /home/ansible_user/.ssh/
        owner: ansible_user
        group: ansible_user
        mode: preserve
        
    - name: disable root access to ssh
      become: true
      replace:
        path: /etc/ssh/sshd_config
        regexp: "#PermitRootLogin yes"
        replace: "PermitRootLogin no"
    
     - name: restart sshd
       become: true
       service:
         name: sshd
         state: restarted
...
